apiVersion: v1
kind: Service 


metadata:
  name: fleetman-queue-service-rel1
  



spec:
  selector:
    name: fleetman-queue-rel1
  ports:
    - name: http 
      port: 8161
      nodePort: 30010
  type: NodePort 
    
  