apiVersion: v1
kind: Pod
metadata:
  name: webapp-1
  labels:
    app: webapp
    release: 0-5
spec:
  containers:
    - name: webapp-1
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5


--- 

apiVersion: v1
kind: Pod 
metadata:
  name: queue 
  labels:
    app: queue
spec:
  containers:
    - name: fleetman-queue-service-1
      image: richardchesterwood/k8s-fleetman-queue:release1
      imagePullPolicy: Never
      

