
apiVersion: apps/v1

kind: Deployment 

metadata:
  name: queue 

spec:
  selector:
    matchLabels:
      app: queue 
  replicas: 1
  template:    # template for pod
    metadata:
      labels:
        app: queue 
    spec:
      containers:
        - name: webapp 
          image: richardchesterwood/k8s-fleetman-queue:release1
          imagePullPolicy: Never


--- 

apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: position-simulator 
spec: 
  selector:
    matchLabels:
      app: position-simulator  
  replicas: 1 
  template: # template for the pod 
    metadata: 
      labels: 
        app: position-simulator 
    spec: 
      containers: 
        - name: webapp 
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env: 
            - name: SPRING_PROFILES_ACTIVE 
              value: production-microservice 



# apiVersion: apps/v1 
# kind: Deployment 
# metadata:
#   name: webapp

# spec:
#  # minReadySeconds: 30
#   selector:
#     matchLabels:
#       app: webapp 
#   replicas: 2
#   template:
#     metadata:
#       labels: 
#         app: webapp
#     spec:
#       containers:
#         - name: webapp 
#           image: richardchesterwood/k8s-fleetman-queue:release1

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp-1
#   labels:
#     app: webapp
#     release: 0-5
# spec:
#   containers:
#     - name: webapp-1
#       image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5


# --- 

# apiVersion: v1
# kind: Pod 
# metadata:
#   name: queue 
#   labels:
#     app: queue
# spec:
#   containers:
#     - name: fleetman-queue-service-1
#       image: richardchesterwood/k8s-fleetman-queue:release1
#       imagePullPolicy: Never
      

